### ISSUE TITLE
Feat: Update UI

### ISSUE THREAD

**Issue by yunruu** [AY2223S1-CS2103T-T12-2/tp#102]
[X] Add associated contacts to tasks in contact's tab side panel
[X] Let task and contact commands switch tabs immediately
[X] Show side panel only when selecting task and command
[X] Style: contact and task tab side panel
[X] Fix: null pointer in list contact and list task commands

**Comment by ShenyiCui** [comment]
Hi! It's always good to be specific in your issue, I know that you probs know what the bugs are and what the updates u have to do are but the rest of us don't haha

Could you maybe be more specific on the updates you are making and the bugs u are fixing? thank youu

**Comment by ShenyiCui** [comment]
Also! Good to note that if its a UI update and no new features are added the label should be `Style: ...`. Furthermore, the best practice is to keep your issues atomic.
