### ISSUE TITLE
[PE-D][Tester D] add_task should notify when the specified contact is not found

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-2/tp#153]
No details provided by bug reporter.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kelvinou01/ped#3

**Comment by Santosh3007** [comment]
## Issue

add_task does not show any error message when adding task with invalid contact index. Task is still being added but command box is not being cleared.

![image](https://user-images.githubusercontent.com/34889879/199562170-d8f32ba5-7c33-492c-a2db-38b90d08658c.png)


## Steps to Replicate

1. Run `add_task n/test d/test dl/12-12-2012 1200 c/1000`

## Suggestion

1. Display error message and don't add contact
2. Or if we want to add contact without associating, make result box display the task added message

**Comment by yunruu** [comment]
Similar to Issue #149:
[Tester B] add_task: inconsistent validation of c/
