### ISSUE TITLE
[PE-D][Tester B] add_contact: overzealous input validation of `p/`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-2/tp#175]
Sample command: `add_contact n/ Bobby B p/ +6590908080 e/bb@bb.bb a/redacted`

As suggested in the tP forum, (https://github.com/nus-cs2103-AY2223S1/forum/issues/347), it may be better to accept symbols in the  phone numbers rather than blocking, as country codes are a legitimate reason to have a symbol in the contact.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jontmy/ped#10

**Comment by jasonqiu212** [comment]
Updated user guide with input constraints of phone number
