### ISSUE TITLE
Fix codecov status badge in `README` page

### ISSUE THREAD

**Issue by jasonqiu212** [AY2223S1-CS2103T-T12-2/tp#24]
## Tasks
- Fix codecov status badge to point to this repository

**Comment by ShenyiCui** [comment]
Isn't this already resolved?
I pushed directly to main without making a PR haha

**Comment by jasonqiu212** [comment]
Currently, if you try clicking on it, the `codecov` badge points to [https://app.codecov.io/gh/nus-cs2103-AY2223S1/tp](https://app.codecov.io/gh/nus-cs2103-AY2223S1/tp), which is the original repo. It should be pointing to our repo [https://app.codecov.io/gh/AY2223S1-CS2103T-T12-2/tp](https://app.codecov.io/gh/AY2223S1-CS2103T-T12-2/tp).

The `Java CI` is correct though.
